### ISSUE TITLE
Proposal to have status/action node together

### ISSUE THREAD

**Issue by fblackburn1** [fblackburn1/node-red-contrib-hubitat#12]
Currently they are nodes that execute a command OR get the state of the device/mode
The concept to send a command and get the state are always been separated.

## Problem
We want to execute AND get state of some specific component. For now, we talk about `mode` and `hsm` node
ex: I want to change the mode from the `mode` node but I want also have something to get its state.

## Solutions
Here some ideas. The solution can also be a mix of these (or other) ideas

1. Do nothing and use `http request` node to send command ...
note: If it's the best solution ... then I guess I can remove the repository :laughing: 

2. Use two different nodes (like the device/command nodes). 
ex: current `mode` node to get the state and  a new node to  set the state
    * pros:
        * use same device/command logic
        * in most use case, one node should do one thing, either giving state either changing state
    * cons:
      * add nodes and complexity to understand the difference
      * choosing a node by the action (get/set) vs by the type (mode, hsm) is less intuitive (IMO)

3. Using node property to choose what the node do.
    1. Using [node-red-contrib-smarthing logic](https://github.com/otaviojr/node-red-contrib-smartthings/blob/master/smartthings/smartthings-level.js#L102). It uses the `topic` property to define what the node should do. Example with `mode` node
       * if `topic = update`, then output message will be the mode state
       * if `topic = mode`, then you also need to set the `payload: {value: Night}`
       * if `topic` is undefined, then output nothing

    2. What is proposed in [the HSM PR](https://github.com/fblackburn1/node-red-contrib-hubitat/pull/9/files#diff-d260730dc72d7e30c99bc66f52a3585cR98). It uses a mix with node property and default node setting to define when to send or set state. Example with `mode` node
        * If input msg don't set `mode` property, then the default command node is executed
           * if the `default mode` is null, then the node returns `mode` state
           * otherwise, the node set the `default mode`
        * If input msg set `mode = Night`, then the node make the request and output the new state
        * If input msg set the `mode = null` property, then the node returns the `mode` state

    3. Mix between `3.i` and `3.ii`. Remove the concept of `default mode` in the node setting. 
        * pros:
           * keep the default behavior when an input message without specific property will output the state
        * cons:
           * We lose available values list (we can mitigate this by adding value/example in the node doc)

**Comment by danfox52** [comment]
I vote for #2. This keeps logic the same as device/command.

**Comment by ashokaiyar** [comment]
#2 - keeps the current convention (and you name the nodes as "mode-state" and "mode-command" to avoid any confusion .....

**Comment by stephennutt** [comment]
I am with them.  #2  I don't see the 1st bullet point under cons as a big deal.

**Comment by MorningZ** [comment]
I don't see the problem with #1 to be honest, it's a simple GET call that takes 5 seconds to set up

/2-cents

**Comment by fblackburn1** [comment]
I'm quite surprised by your answers. If it was not clear, there are no solution hard to implement (even doing nothing `#1` is not harder than `#3` :wink: ). Maybe I'm asking myself too many questions :sweat_smile: 

For solution `#3` here a sample of `mode` node with a default action (much easier to understand with image)
![Screenshot from 2020-03-24 19-23-42](https://user-images.githubusercontent.com/11160579/77486446-26eac280-6e06-11ea-9cf9-cfa81e444104.png)

But yeah the real question is about merging state and action or not.
So your answers about keeping separate things come with another question: Does the action should be merge with the `command` node? Like faking first two devices to `mode` and `hsm` ?

You can also give me the answer: "I don't care about your sh*tty dilemma, just release the feature". It will also be useful ;)

Thank you for your answers. I can't guarantee that I won't just do it my way, but i will definitely take it into account :grin:

**Comment by ashokaiyar** [comment]
> But yeah the real question is about merging state and action or not.

Merging them will keep the number of nodes down. However, people who start out using node-red-contrib-hubitat may find it confusing that for Devices there are different state and action nodes, but that HSM and Mode have a single node that does both ....

**Comment by Botched1** [comment]
#2 more closely matches the standard Node-Red node philosophy. Typically in/out nodes are separate nodes with fixed purpose, as opposed to more complex all-in-one nodes.

That said, I am OK with 2 or 3. Number 1 is not very new user friendly, even though it is technically easy to do.
