### ISSUE TITLE
Add option to disable logging

### ISSUE THREAD

**Issue by robacarp** [fblackburn1/node-red-contrib-hubitat#121]
Hi @fblackburn1, I notice that my node-red log is growing incredibly. 

![image](https://user-images.githubusercontent.com/208647/153440679-0d80c2f1-4742-49bd-9bed-3cd7d3554c1c.png)

Is it possible to add an option to the Hubitat config to decrease the logging verbosity?

**Comment by robacarp** [comment]
Good point. I checked my settings.json, and the log level is set to info. The messages are from event.js as far as I can tell.

Here are the three messages I see:

```
 11 Feb 10:42:29 - [info] [hubitat event:All Events] Event: temperature
 11 Feb 10:42:29 - [info] [hubitat event:6657c34fc5526365] Event: temperature
 11 Feb 10:42:29 - [info] [hubitat device:8c649af674c27f6f] temperature: 70.25
```

I think those are probably all covered by the two lines you found. Aside from messages which are tagged as `[hubbitat ...]` the only messages that show up in my log are from node-red itself, eg: `Starting flows`.

**Comment by fblackburn1** [comment]
Hum ok, I will check to change these logs to verbose only
Quick workaround:
* edit: `node_modules/node-red-contrib-hubitat/nodes/event.js`
* remove line 18
```diff
- node.log(`Event: ${event.name}`);
```
