### ISSUE TITLE
How to tell Hubitat that garage door is opening or closing

### ISSUE THREAD

**Issue by k5map** [fblackburn1/node-red-contrib-hubitat#152]
Currently I have NR interfaced to a virtual Garage Door in Hubitat.  Since Hubitat does not "manage" the garage door, I am attempting to send the current device status to Hubitat to accurately reflect the status on the dashboard (i.e. opening or closing).  I can only send open or close via the control node.  What is the proper way to update the device status in Hubitat?

**Comment by fblackburn1** [comment]
By "control node" did you mean "command node"?
Using this node would be my guest too
During development of these nodes, I did see any API to only update status, maybe you could ask on Hubitat forum
If you find an API, you could use the "request node" which will handle all authentication for you

**Comment by k5map** [comment]
@fblackburn1 ... oops, yes; I meant Command node.  My end goal is to show on the Hubitat dashboard the status of "opening" and "closing" on the virtual Garage door tile.  Specifically, the dashboard tile would change from "open" to "closing" then "close" (and the opposite).  Currently, I can click on the tile and do this manually but was looking for a way to do this from NR to HE since NR has the interface to the garage door.  I'm open to any suggestions you might have to accomplish this.

**Comment by fblackburn1** [comment]
Using the command node is what I would do
If I understand correctly, your "real" device is directly on NR (through another set of nodes)?
I don't see anything wrong with sending a "fake" command to HE to update the status

I don't have better solution for you
But don't hesitate to ask on the Hubitat Forum, this community is really creative :smile:

**Comment by k5map** [comment]
Correct... NR is actually the interface to the opener.  My problem is when I send "opening" or "closing" to the Command mode, I get an error and the virtual Garage Door in HE does not change status (only shows Open or Closed).  I'll give the HE NR forum a try.  Thanks again.

**Comment by fblackburn1** [comment]
Oh well if you get an error it's the first thing you must say :smile: 
What is the error you have?
I setup a virtual garage door controller and don't have any issue
![garage-door](https://user-images.githubusercontent.com/11160579/234428102-510fbf79-aad9-4a27-b9cd-86b13c1f72bb.gif) 
(the 5 sec delay when sending close is the transition time configured in the driver)
