### ISSUE TITLE
Allow expression to the `Arguments` field of the `command` node

### ISSUE THREAD

**Issue by fblackburn1** [fblackburn1/node-red-contrib-hubitat#153]
From https://community.hubitat.com/t/node-red-nodes-for-hubitat/34386/5235

> Would it be possible to add expressions to the Arguments field of the Command node?
>Something like {{msg.payload.value}}.
>
>I can add a Change node and set the msg.arguments there, but I'd rather have less nodes and use the original message.
>
>Currently I find myself always having to add a Change node before a Command node.

**Comment by BUMPRW** [comment]
I Tried the change node method.  Could you provide an example?  I was taking a number from mysql essentially a msg.payload.value and I tried it have a dozen ways and still could not get it into Hubitat.  So I agree being able to add an expression into Command Node arguments would be invaluable.  I was trying to send the internal humidity value from a Davis Weather Station to a variable in Hubitat.

**Comment by BUMPRW** [comment]
no comment

**Comment by fblackburn1** [comment]
`msg.requestCommand` and `msg.requestArguments` are the **output** of the node
If you want to set command and arguments you should set `msg.command` and `msg.arguments`

![Uploading Screenshot from 2023-08-26 16-22-46.png…]()


But thank you, you give me the opportunity to test variable with Hubitat :smile:

**Comment by BUMPRW** [comment]
I tried what you suggested as a string and number but neither worked.  It does work from the command node, but that is a keyboard input.  This is my setup, the output is on debug 2, the node above does work fine, this is my second option:
![Screenshot 2023-08-26 at 19 36 01](https://github.com/fblackburn1/node-red-contrib-hubitat/assets/19250829/22ba5e78-ab77-43f0-9b33-ccbec2733e2c)
![Screenshot 2023-08-26 at 17 59 10](https://github.com/fblackburn1/node-red-contrib-hubitat/assets/19250829/12e64145-c293-4088-808e-1715a71019a5)

**Comment by BUMPRW** [comment]
This is the message output on my terminal:
26 Aug 19:48:57 - [info] [debug:debug 2] 
{
  payload: [ RowDataPacket { Time: 2023-08-27T05:48:51.000Z, HumidityInt: 46 } ],
  _msgid: 'XXXXXXXXXXXXXXXXXXXX',
  requestCommand: 'setHumidity',
  requestArguments: '',
  responseStatus: 200,
  response: {
    id: '680',
    name: 'HumidityInt',
    label: 'HumidityInt',
    type: 'Virtual Humidity Sensor',
    room: 'Living Room',
    attributes: [ { name: 'humidity', currentValue: 22, dataType: 'NUMBER' } ],
    capabilities: [
      'RelativeHumidityMeasurement',
      { attributes: [ { name: 'humidity', dataType: null } ] }
    ],
    commands: [ 'setHumidity' ]
  },
  command: 'setHumidity',
  arguments: 46
}
Thanks also, I'm just a beginner at this  . . . sort of, but any assistance is much appreciated.

**Comment by BUMPRW** [comment]
This is the error message in the Hubitat log:
[dev:680](http://192.168.1.39/logs#)2023-08-26 19:56:34.450[error](http://xxx.xxx.x.xx/logs#)java.lang.NullPointerException: Cannot invoke method toInteger() on null object on line 28 (method setHumidity)

This is just me thinking out-loud: The message goes out in string format, i.e. "44" and the Hubitat sees it as an error and rejects the command.

**Comment by fblackburn1** [comment]
@BUMPRW The change node must be done before command node.
You must see node red as a flow. Using `command` node before anything will trigger command (with empty `msg.arguments`) and will make the request failing.
To help you, you should add debug node before/after every node to know what was the input/output. Also, start by using simple logic (ex: use change node to hardcode 44 like my example, then when it works, use more advance logic)
If you want more step-by-step / quick help, do not hesitate to ask on the hubitat forum on node-red section: https://community.hubitat.com/c/comappsanddrivers/nodered/105

**Comment by BUMPRW** [comment]
That worked.  I had tried this before, but with “Arguments” vs. “arguments”  and many other things, so . . . I didn’t think that worked.  As soon as I changed it to “arguments” my database is feeding it fine.

Thanks!,

RWB
