### ISSUE TITLE
Feature Request: Include a device's room in the json

### ISSUE THREAD

**Issue by jimko** [fblackburn1/node-red-contrib-hubitat#160]
Each device in Hubitat has an optional Room assignment. I'd like to see that data element returned with status messages from the "events" node. My use case would be to use the room as the prefix to mqtt topic, and then be able to organize my flows better by room.  This might need to be done in the Maker API on the Hubitat side, but I thought I try asking here first. 

Some sort of static (device,room) map might work too. As long as it re-cached all the data periodically, I could look up the room for any device before putting into mqtt without a round-trip to query Hubitat. 

Thanks for consideration

**Comment by fblackburn1** [comment]
Unfortunately, we don't have `room` info in events. You can view the plain content sent by Maker API with the `event` node

Getting room for each device on initialization would be the most viable solution. But as you said, the challenge would be to make this cache dynamic. The ideal solution would be to have a event when you change room attribute for a device ... but we don't (I guess)
Any other mechanism would have some tradeoffs and complexity, that I'm not sure I want to add to these, already complex, nodes (but open to discussion pros/cons)
As workaround, I guess you can create this mapping with a flow and node-red variables

**Comment by jimko** [comment]
Thanks for considering it. After working with NR & Hubitat in the meantime,
I've realized the room-based approach was not working out as I had hoped
anyway.
