### ISSUE TITLE
Get all device events for devices with capability?

### ISSUE THREAD

**Issue by robacarp** [fblackburn1/node-red-contrib-hubitat#21]
Currently, in order to produce a dashboard graph of all my battery powered devices, I need to add N nodes to my NodeRED flow:

```
[Device1 - Battery] -> [Battery Graph]
[Device{n} - Battery] -> [Battery Graph]
...
```

I'd like to be able to do something like this:

```
[Capability(Battery)] -> [Battery Graph]
[Capability(Temperature)] -> [Temperature Graph]
```

The messages coming out of the Device Capability node would emit messages like the current Device node, but would focus on devices which all have a given capability.

I'd really like to be able to do this too, but it requires more than just a capability node, it requires a command node with the ability to specify device at execution time:

```
[Capability(Color Temperature)] -> [Switch: State=on] -> [Command(Device: <message.payload.deviceId>, ColorTemperature: Flow.ColorTemperature]
```

Hopefully that makes sense. I'm not sure what the best way to go about diagramming theoretical nodes is.

**Comment by fblackburn1** [comment]
Thank you for the suggestion, If I understand what you want:
1. capability node
2. remove device required on command node

With the first request, there are two (small) technically issues/limitations
1. From what I've read, the endpoint to get all devices can be a little slow when there is a lot of devices. Which would be necessary to initiate the node and know all capability devices
2. Each time we add or remove device from Maker API allowed device, we would need to restart Node-RED (to re-initiate the node)

The second request, well my opinion is that if you want a command node without specify device, than you probably should use http request node (with maybe a template node). But I know there are other people that want this too .. I guess I need to try myself to use http request node with template to see if it's really painful

I am not entirely convinced by utility of a capability node. Because you can add a http-in request to receive all events and filtered by capability with another node. In the next days I will have some free time to dedicate on it, I will think a little bit more

**Comment by robacarp** [comment]
A generic event node seems like it might be useful in all sorts of ways! I assumed that the maker api would have some way of registering for a capability since the ecosystem is so tied to the idea of devices by capability, but if not I get what you mean about not having the easy ability to list all devices with a capability.

**Comment by fblackburn1** [comment]
With the event and request nodes, you can now create the flow you want (disclaimer: I'm really bad with dashboard :laughing: )

![Screenshot from 2020-04-17 17-20-11](https://user-images.githubusercontent.com/11160579/79615359-93d53d80-80d0-11ea-875b-c69f7cbcf3cb.png)

```json
[{"id":"45d2924b.0eca5c","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"2ebe5c49.1fb89c","type":"hubitat event","z":"45d2924b.0eca5c","name":"","server":"aeaecfe5.e3c678","x":290,"y":80,"wires":[["2c595ae4.72a4b6"]]},{"id":"4e3a65e.cead49c","type":"hubitat request","z":"45d2924b.0eca5c","name":"Get Devices","server":"aeaecfe5.e3c678","path":"/devices/all","x":270,"y":140,"wires":[["b821bd7b.0d9d3"]]},{"id":"d72f2565.13b258","type":"inject","z":"45d2924b.0eca5c","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":110,"y":140,"wires":[["4e3a65e.cead49c"]]},{"id":"b821bd7b.0d9d3","type":"split","z":"45d2924b.0eca5c","name":"Split","splt":"\\n","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"","x":430,"y":140,"wires":[["2c534ea5.d8a5da"]]},{"id":"2c534ea5.d8a5da","type":"switch","z":"45d2924b.0eca5c","name":"","property":"payload.attributes","propertyType":"msg","rules":[{"t":"hask","v":"battery","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":570,"y":140,"wires":[["63468155.01ed"]]},{"id":"63468155.01ed","type":"change","z":"45d2924b.0eca5c","name":"set value","rules":[{"t":"set","p":"topic","pt":"msg","to":"payload.label","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"payload.attributes.battery","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":740,"y":140,"wires":[["5bf745e9.61a30c"]]},{"id":"5bf745e9.61a30c","type":"ui_chart","z":"45d2924b.0eca5c","name":"","group":"9ad6e619.cdab7","order":1,"width":0,"height":0,"label":"{{msg.topic}}","chartType":"horizontalBar","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"0","ymax":"100","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"useOneColor":true,"useUTC":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":910,"y":100,"wires":[[]]},{"id":"6ecf5c98.00a87c","type":"change","z":"45d2924b.0eca5c","name":"set value","rules":[{"t":"set","p":"topic","pt":"msg","to":"payload.displayName","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"payload.value","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":740,"y":80,"wires":[["5bf745e9.61a30c"]]},{"id":"2c595ae4.72a4b6","type":"switch","z":"45d2924b.0eca5c","name":"","property":"payload.name","propertyType":"msg","rules":[{"t":"eq","v":"battery","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":570,"y":80,"wires":[["6ecf5c98.00a87c"]]},{"id":"9ad6e619.cdab7","type":"ui_group","z":"","name":"Default","tab":"68d5add8.ad02a4","disp":true,"width":"6","collapse":false},{"id":"68d5add8.ad02a4","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]
```

**Comment by robacarp** [comment]
Working as in the latest release! Thank you @fblackburn1
