### ISSUE TITLE
Allow to retrieve all atribute for a device

### ISSUE THREAD

**Issue by fblackburn1** [fblackburn1/node-red-contrib-hubitat#22]
As user I want to be able to retrieve all attributes from a device

Proposal
Rename the `undefined` select attribute to `all`
If you input a message, then the output will be
```json
"payload": {
    "level": {
        "value": 50,
        "dataType": "NUMBER"
    },
    "switch": {
        "value": "on",
        "dataType": "ENUM"
    }
    ...
}
```
But when a event is received, only the event attribute is sent:
```json
"payload": {
  "name": "contact",
  "value": "closed"
}
```

**Comment by adsavia** [comment]
Yes that looks good to me. Thank you.
- ErkTrek
