### ISSUE TITLE
Getting an error in Node-Red Logs on node initialization.

### ISSUE THREAD

**Issue by adsavia** [fblackburn1/node-red-contrib-hubitat#36]
> 14 May 09:45:25 - [info] [hubitat device:Mud Room Door Sensor 2] Initialized. contact: closed
> 14 May 09:45:25 - [info] [hubitat device:Mud Room Door Sensor 2] Fix "threeAxis" attribute desynchronization: "[object Object]" --> "[object Object]"
> (node:1188) UnhandledPromiseRejectionWarning: TypeError: value.match is not a function
>     at castHubitatValue (/home/node-red/.node-red/node_modules/node-red-contrib-hubitat/nodes/device.js:26:38)
>     at eventCallback (/home/node-red/.node-red/node_modules/node-red-contrib-hubitat/nodes/device.js:109:25)
>     at /home/node-red/.node-red/node_modules/node-red-contrib-hubitat/nodes/device.js:144:11
>     at Array.forEach (<anonymous>)
>     at EventEmitter.systemStartCallback (/home/node-red/.node-red/node_modules/node-red-contrib-hubitat/nodes/device.js:136:10)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:1188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by fblackburn1** [comment]
Thank you for report, I can see what is the issue :+1:
