### ISSUE TITLE
Feature Request: Update command node to handle multiple devices or create a new Group Command Node

### ISSUE THREAD

**Issue by adsavia** [fblackburn1/node-red-contrib-hubitat#41]
Have ability to select multiple devices in a command node (or separate group node). Everything would be the same but commands would be applied across multiple devices.

**Comment by adsavia** [comment]
Thanks for your post on the community.. did not realize I could use Device ID.. am good!!! thanks.

**Comment by fblackburn1** [comment]
not one could realize that deviceId was available, the doc was missing :sweat_smile: 
It [fix it](https://github.com/fblackburn1/node-red-contrib-hubitat/commit/70305fdbd42ec8f864d94f7d2ccfd752d7686624) and will be available in an upcoming release
Thanks :+1:
