### ISSUE TITLE
Consider changing online node help to specify full input parameters

### ISSUE THREAD

**Issue by Botched1** [fblackburn1/node-red-contrib-hubitat#43]
People have been confused a number of times on the allowable/format of input attributes.

Consider changing the onlying help to include "msg." on the attributes. For example, on the command node change help to say:
"msg.deviceId" instead of "deviceId"
"msg.command" instead of "command"
"msg.arguments" instead of "arguments"

Similar to how Pushover did theirs:
![image](https://user-images.githubusercontent.com/19985320/86483291-59fff480-bd19-11ea-9d26-1319aad44162.png)

**Comment by ashokaiyar** [comment]
This is a really good idea! Now if there was only a way to force someone to read the help for a node the first time they used it! :-)
