### ISSUE TITLE
Sending invalid values for setLevel command

### ISSUE THREAD

**Issue by Botched1** [fblackburn1/node-red-contrib-hubitat#52]
It has come up a few times where users have reported Hubitat errors when using the node-red nodes. It turns out that in these cases they were sending a null/space/blank for the argument on a command node setLevel command.

I'm not sure it is worth coding around this user issue or not, but I thought I would mention it in case you can think of an easy way for the node to not send null/space/blank for setLevel?

Example below. For setLevel the 1st argument is required the second is optional. Again, it is user error when it happens, so it might not be worth trapping:
![image](https://user-images.githubusercontent.com/19985320/88350174-e6e60e80-cd17-11ea-9430-2a0ec5444575.png)

**Comment by Botched1** [comment]
[](url)

**Comment by fblackburn1** [comment]
Can we generalize to all commands?
* if only space found in arguments, then save nothing
* if space found around (at the end/start) of the argument, then strip them?

Or it can cause some issue with some commands (ex: speaking device?)

**Comment by Botched1** [comment]
I looked at this, and it does cause issues in a few scenarios.

I think I'll just close this. While I like to protect user mis-input when possible, this does not seem worth the effort.
