### ISSUE TITLE
"Unable to cast to dataType. Open an issue to report back the following output: BOOLEAN: false"

### ISSUE THREAD

**Issue by jpoeppelman1** [fblackburn1/node-red-contrib-hubitat#67]
11/13/2020, 4:24:46 AMnode: Hubitat HubConnect
msg : string[93]
"Unable to cast to dataType. Open an issue to report back the following output: BOOLEAN: false"

Can we put the device ID in this error message?

**Comment by fblackburn1** [comment]
Sure :+1:
This error is because you should have a community/custom driver that send `BOOLEAN` instead of the documented `BOOL`
https://docs.hubitat.com/index.php?title=Attribute_Object

**Comment by fblackburn1** [comment]
It will be in the next release

**Comment by jpoeppelman1** [comment]
Thanks for looking into this. So is it a bug or problem with the custom HE
driver?

**Comment by fblackburn1** [comment]
I added the device ID in the message, then after the upgrade you will have the following message instead:
```
Unable to cast to dataType for device ID (123) with attribute (my-attribute).
Open an issue (https://github.com/fblackburn1/node-red-contrib-hubitat/issues) to report back the following output: BOOLEAN: false
```
You will be able to identify which device send the `BOOLEAN` dataType. If your device use: 
* non-official driver: then you should ask a fix to the maintainer of this driver.
* official driver: then come back here and I will add the `BOOLEAN` type
  * also we will need to ask to update the Hubitat wiki with this *new* `dataType`

**Comment by jpoeppelman1** [comment]
Thank you for adding the device ID!
